<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class SekolahSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'nama_sekolah' => 'UPTD TK NEGERI PEMBINA KEC. LINTAU BUO',
                'tingkatan' => 'TK',
                'akreditasi' => null,
                'npsn' => '10308727',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Lintau Buo, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Lintau Buo',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'SD ISLAM TERPADU NURUL UMMAH TIGO JANGKO',
                'tingkatan' => 'SD',
                'akreditasi' => null,
                'npsn' => '70032483',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Lintau Buo, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Lintau Buo',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPT SDN 01 PANGIAN',
                'tingkatan' => 'SD',
                'akreditasi' => null,
                'npsn' => '10302538',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Lintau Buo, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Lintau Buo',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPT SDN 02 TALUAK',
                'tingkatan' => 'SD',
                'akreditasi' => null,
                'npsn' => '10302542',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Lintau Buo, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Lintau Buo',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPT SDN 03 TIGO JANGKO',
                'tingkatan' => 'SD',
                'akreditasi' => null,
                'npsn' => '10307879',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Lintau Buo, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Lintau Buo',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPT SDN 04 BUO',
                'tingkatan' => 'SD',
                'akreditasi' => null,
                'npsn' => '10302713',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Lintau Buo, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Lintau Buo',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPT SDN 05 TIGO JANGKO',
                'tingkatan' => 'SD',
                'akreditasi' => null,
                'npsn' => '10302691',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Lintau Buo, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Lintau Buo',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPT SDN 06 TALUAK',
                'tingkatan' => 'SD',
                'akreditasi' => null,
                'npsn' => '10302635',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Lintau Buo, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Lintau Buo',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPT SDN 07 PANGIAN',
                'tingkatan' => 'SD',
                'akreditasi' => null,
                'npsn' => '10302284',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Lintau Buo, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Lintau Buo',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPT SDN 08 TIGO JANGKO',
                'tingkatan' => 'SD',
                'akreditasi' => null,
                'npsn' => '10302275',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Lintau Buo, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Lintau Buo',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPT SDN 09 TALUAK',
                'tingkatan' => 'SD',
                'akreditasi' => null,
                'npsn' => '10302311',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Lintau Buo, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Lintau Buo',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPT SDN 10 TIGO JANGKO',
                'tingkatan' => 'SD',
                'akreditasi' => null,
                'npsn' => '10302441',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Lintau Buo, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Lintau Buo',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPT SDN 11 TALUAK',
                'tingkatan' => 'SD',
                'akreditasi' => null,
                'npsn' => '10307880',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Lintau Buo, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Lintau Buo',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPT SDN 12 PANGIAN',
                'tingkatan' => 'SD',
                'akreditasi' => null,
                'npsn' => '10302488',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Lintau Buo, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Lintau Buo',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPT SDN 13 TIGO JANGKO',
                'tingkatan' => 'SD',
                'akreditasi' => null,
                'npsn' => '10302489',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Lintau Buo, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Lintau Buo',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPT SMPN 1 LINTAU BUO',
                'tingkatan' => 'SMP',
                'akreditasi' => null,
                'npsn' => '10302425',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Lintau Buo, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Lintau Buo',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPT SMPN 2 LINTAU BUO',
                'tingkatan' => 'SMP',
                'akreditasi' => null,
                'npsn' => '10302416',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Lintau Buo, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Lintau Buo',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPT SMPN 3 LINTAU BUO',
                'tingkatan' => 'SMP',
                'akreditasi' => null,
                'npsn' => '10308114',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Lintau Buo, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Lintau Buo',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPTD TK NEGERI 01 KEC. PADANG GANTING',
                'tingkatan' => 'TK',
                'akreditasi' => null,
                'npsn' => '10308743',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Padang Ganting, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Padang Ganting',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPTD TK NEGERI PEMBINA KEC. PADANG GANTING',
                'tingkatan' => 'TK',
                'akreditasi' => null,
                'npsn' => '10308738',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Padang Ganting, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Padang Ganting',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPT SDN 01 ATAR',
                'tingkatan' => 'SD',
                'akreditasi' => null,
                'npsn' => '10302525',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Padang Ganting, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Padang Ganting',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPT SDN 02 PADANG GANTING',
                'tingkatan' => 'SD',
                'akreditasi' => null,
                'npsn' => '10302547',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Padang Ganting, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Padang Ganting',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPT SDN 03 PADANG GANTING',
                'tingkatan' => 'SD',
                'akreditasi' => null,
                'npsn' => '10302707',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Padang Ganting, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Padang Ganting',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPT SDN 04 PADANG GANTING',
                'tingkatan' => 'SD',
                'akreditasi' => null,
                'npsn' => '10302622',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Padang Ganting, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Padang Ganting',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPT SDN 05 PADANG GANTING',
                'tingkatan' => 'SD',
                'akreditasi' => null,
                'npsn' => '10302630',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Padang Ganting, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Padang Ganting',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPT SDN 06 PADANG GANTING',
                'tingkatan' => 'SD',
                'akreditasi' => null,
                'npsn' => '10302614',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Padang Ganting, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Padang Ganting',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPT SDN 07 ATAR',
                'tingkatan' => 'SD',
                'akreditasi' => null,
                'npsn' => '10302653',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Padang Ganting, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Padang Ganting',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPT SDN 08 ATAR',
                'tingkatan' => 'SD',
                'akreditasi' => null,
                'npsn' => '10302320',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Padang Ganting, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Padang Ganting',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPT SDN 09 PADANG GANTING',
                'tingkatan' => 'SD',
                'akreditasi' => null,
                'npsn' => '10302376',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Padang Ganting, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Padang Ganting',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPT SDN 10 ATAR',
                'tingkatan' => 'SD',
                'akreditasi' => null,
                'npsn' => '10302357',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Padang Ganting, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Padang Ganting',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPT SDN 11 PADANG GANTING',
                'tingkatan' => 'SD',
                'akreditasi' => null,
                'npsn' => '10302285',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Padang Ganting, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Padang Ganting',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPT SDN 12 ATAR',
                'tingkatan' => 'SD',
                'akreditasi' => null,
                'npsn' => '10302261',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Padang Ganting, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Padang Ganting',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPT SDN 13 PADANG GANTING',
                'tingkatan' => 'SD',
                'akreditasi' => null,
                'npsn' => '10302312',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Padang Ganting, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Padang Ganting',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPT SMPN 1 PADANG GANTING',
                'tingkatan' => 'SMP',
                'akreditasi' => null,
                'npsn' => '10302387',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Padang Ganting, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Padang Ganting',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPT SMPN 2 PADANG GANTING',
                'tingkatan' => 'SMP',
                'akreditasi' => null,
                'npsn' => '10302426',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Padang Ganting, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Padang Ganting',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPTD TK NEGERI PEMBINA KAB. TANAH DATAR',
                'tingkatan' => 'TK',
                'akreditasi' => null,
                'npsn' => '10308784',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Tanjung Emas, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Tanjung Emas',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPTD TK NEGERI PEMBINA KEC. TANJUNG EMAS',
                'tingkatan' => 'TK',
                'akreditasi' => null,
                'npsn' => '10308782',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Tanjung Emas, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Tanjung Emas',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPT SDN 01 PAGARUYUNG',
                'tingkatan' => 'SD',
                'akreditasi' => null,
                'npsn' => '10302536',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Tanjung Emas, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Tanjung Emas',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPT SDN 02 TANJUNG BARULAK',
                'tingkatan' => 'SD',
                'akreditasi' => null,
                'npsn' => '10302535',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Tanjung Emas, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Tanjung Emas',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPT SDN 03 KOTO TANGAH',
                'tingkatan' => 'SD',
                'akreditasi' => null,
                'npsn' => '10307624',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Tanjung Emas, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Tanjung Emas',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPT SDN 04 SARUASO',
                'tingkatan' => 'SD',
                'akreditasi' => null,
                'npsn' => '10302663',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Tanjung Emas, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Tanjung Emas',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPT SDN 05 SARUASO',
                'tingkatan' => 'SD',
                'akreditasi' => null,
                'npsn' => '10302670',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Tanjung Emas, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Tanjung Emas',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPT SDN 06 SARUASO',
                'tingkatan' => 'SD',
                'akreditasi' => null,
                'npsn' => '10302702',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Tanjung Emas, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Tanjung Emas',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPT SDN 07 TANJUNG BARULAK',
                'tingkatan' => 'SD',
                'akreditasi' => null,
                'npsn' => '10302695',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Tanjung Emas, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Tanjung Emas',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPT SDN 08 PAGARUYUNG',
                'tingkatan' => 'SD',
                'akreditasi' => null,
                'npsn' => '10302646',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Tanjung Emas, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Tanjung Emas',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPT SDN 09 SARUASO',
                'tingkatan' => 'SD',
                'akreditasi' => null,
                'npsn' => '10302639',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Tanjung Emas, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Tanjung Emas',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPT SDN 10 KOTO TANGAH',
                'tingkatan' => 'SD',
                'akreditasi' => null,
                'npsn' => '10302331',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Tanjung Emas, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Tanjung Emas',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPT SDN 11 TANJUNG BARULAK',
                'tingkatan' => 'SD',
                'akreditasi' => null,
                'npsn' => '10302338',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Tanjung Emas, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Tanjung Emas',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPT SDN 12 PAGARUYUNG',
                'tingkatan' => 'SD',
                'akreditasi' => null,
                'npsn' => '10302353',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Tanjung Emas, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Tanjung Emas',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPT SDN 13 SARUASO',
                'tingkatan' => 'SD',
                'akreditasi' => null,
                'npsn' => '10302362',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Tanjung Emas, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Tanjung Emas',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPT SDN 14 TANJUNG BARULAK',
                'tingkatan' => 'SD',
                'akreditasi' => null,
                'npsn' => '10302315',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Tanjung Emas, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Tanjung Emas',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPT SDN 15 PAGARUYUNG',
                'tingkatan' => 'SD',
                'akreditasi' => null,
                'npsn' => '10302270',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Tanjung Emas, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Tanjung Emas',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPT SDN 16 SARUASO',
                'tingkatan' => 'SD',
                'akreditasi' => null,
                'npsn' => '10302308',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Tanjung Emas, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Tanjung Emas',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPT SDN 17 SARUASO',
                'tingkatan' => 'SD',
                'akreditasi' => null,
                'npsn' => '10302289',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Tanjung Emas, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Tanjung Emas',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPT SDN 18 SARUASO',
                'tingkatan' => 'SD',
                'akreditasi' => null,
                'npsn' => '10307878',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Tanjung Emas, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Tanjung Emas',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPT SMPN 1 TANJUNG EMAS',
                'tingkatan' => 'SMP',
                'akreditasi' => null,
                'npsn' => '10302393',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Tanjung Emas, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Tanjung Emas',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPT SMPN 2 TANJUNG EMAS',
                'tingkatan' => 'SMP',
                'akreditasi' => null,
                'npsn' => '10302432',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Tanjung Emas, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Tanjung Emas',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama_sekolah' => 'UPT SMPN 3 TANJUNG EMAS',
                'tingkatan' => 'SMP',
                'akreditasi' => null,
                'npsn' => '10308130',
                'nomor_sekolah' => null,
                'email' => null,
                'website' => null,
                'alamat' => 'Kecamatan Tanjung Emas, Kabupaten Tanah Datar, Sumatera Barat',
                'latitude' => -0.46000000,
                'longitude' => 100.57000000,
                'kecamatan' => 'Tanjung Emas',
                'geojson_id' => null,
                'foto' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ];

        $this->db->table('sekolah')->insertBatch($data);
    }
}
